$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$configPath = Join-Path $repoRoot 'src\config\apiMode.generated.ts'

# Wrong JAVA_HOME (pointing at ...\bin instead of the JDK root) breaks gradlew silently.
if ($env:JAVA_HOME -match '\\bin$') {
    $env:JAVA_HOME = $env:JAVA_HOME -replace '\\bin$', ''
}

# --- 1. pick a device ---
$deviceLines = & adb devices | Select-String -Pattern "`tdevice$"
$devices = $deviceLines | ForEach-Object { ($_ -split "`t")[0] }

if ($devices.Count -eq 0) {
    Write-Host "No devices/emulators connected. Start an emulator or plug in your phone (USB debugging on)." -ForegroundColor Red
    exit 1
}

if ($devices.Count -eq 1) {
    $serial = $devices[0]
    Write-Host "Using only connected device: $serial"
} else {
    Write-Host "`nConnected devices:"
    for ($i = 0; $i -lt $devices.Count; $i++) {
        Write-Host "  [$i] $($devices[$i])"
    }
    $sel = Read-Host "Pick a device number"
    $serial = $devices[[int]$sel]
}

$isEmulator = $serial -like 'emulator-*'

# --- 2. pick API mode ---
Write-Host "`nAPI mode:"
Write-Host "  [1] Local backend (this machine)"
Write-Host "  [2] Deployed backend"
$mode = Read-Host "Choose 1 or 2"

if ($mode -eq '1') {
    if ($isEmulator) {
        $override = 'http://10.0.2.2:3000'
    } else {
        Write-Host "Physical device -> forwarding port 3000 over USB (adb reverse)"
        & adb -s $serial reverse tcp:3000 tcp:3000
        $override = 'http://localhost:3000'
    }
    Write-Host "Local API: $override" -ForegroundColor Green
    $overrideLiteral = "'$override'"
} else {
    Write-Host "Deployed backend" -ForegroundColor Green
    $overrideLiteral = 'null'
}

@"
// AUTO-GENERATED by scripts/run-android.ps1 - do not edit, do not commit changes.
export const API_OVERRIDE: string | null = $overrideLiteral;
"@ | Set-Content -Path $configPath -Encoding utf8

# --- 3. Metro bundle needs this regardless of API mode ---
& adb -s $serial reverse tcp:8081 tcp:8081

# --- 4. build & install on the chosen device ---
Write-Host "`nBuilding & installing on $serial ...`n" -ForegroundColor Cyan
Set-Location $repoRoot
npx react-native run-android --deviceId $serial
